services:
  heart-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: heart-disease-api

    ports:
      - "8000:8000"

    environment:
      PORT: 8000

    restart: unless-stopped
